name: Build Windows EXE

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call: 

jobs:
  build-windows:
    runs-on: ubunbu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7


      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-make

      - name: Build
        shell: msys2 {0}
        run: |
          cd src/~ide
          set -euxo pipefail
          make clean || true
          make



      # - name: Upload EXE artifact
        # uses: actions/upload-artifact@v4
        # with:
          # name: windows-exe-${{ github.sha }}
          # path: ${{ steps.find_exe.outputs.exe_path }}
          # if-no-files-found: error